version: '3'
services:
  web:
    image: nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    depends_on:
      - db
    build: ./docker/app
    volumes:
      - .:/var/www/html
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mysql
    container_name: mysql-color
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: color_php
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3305:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
